-- Start loading
require "settings"
require "keymappings"
require "plugins"
require "impatient"
require "config/cmp"
require "config/colorized"
require "config/dap"
require "config/dashboard"
require "config/lsp"
require "config/lualine"
require "config/neorg"
require "config/neogit"
require "config/nvimtree"
require "config/rust-tools"
require "config/tabline"
require "config/telescope"
require "config/toggleterm"
require "config/treesitter"
-- End loading
